from django_swagger_utils.drf_server.utils.decorator.interface_decorator \
    import validate_decorator
from .validator_class import ValidatorClass


@validate_decorator(validator_class=ValidatorClass)
def api_wrapper(*args, **kwargs):
    request_data = kwargs['request_data']
    user_id = request_data['user_id']
    referral_code = request_data['referral_code']

    from ib_users.interactors.referrals_interactor import ReferralsInteractor
    from ib_users.presenters.referrals_presenter_impl import ReferralsPresenter
    from ib_users.storages.referrals_storage_impl import ReferralsSQLStorage

    referrals_storage = ReferralsSQLStorage()
    referrals_presenter = ReferralsPresenter()

    referrals_interactor = ReferralsInteractor(storage=referrals_storage,
                                               presenter=referrals_presenter)

    from ib_users.exceptions.referral_exceptions import InvalidReferralCode
    from ib_users.exceptions.referral_exceptions import MaximumReferralsReached
    from django_swagger_utils.drf_server.exceptions import BadRequest
    from ib_users.exceptions.referral_exceptions import \
        ReferralDetailsDoesNotExist
    from ib_users.exceptions.referral_exceptions import ReferrerAlreadyExists
    try:
        referrals_interactor.link_user_with_referrer(
            user_id=user_id, referral_code=referral_code)
    except InvalidReferralCode as error:
        from ib_users.exceptions.custom_exception_constants import \
            ExceptionMessages
        raise BadRequest(res_status=error.error_type,
                         message=error.message)
    except MaximumReferralsReached as error:
        raise BadRequest(res_status=error.error_type,
                         message=error.message)
    except ReferralDetailsDoesNotExist as error:
        raise BadRequest(res_status=error.error_type,
                         message=error.message)
    except ReferrerAlreadyExists as error:
        raise BadRequest(res_status=error.error_type,
                         message=error.message)
